namespace: wanderlust

frontend:
  serviceName: frontend-service
  servicePort: 5173

ingress:
  enabled: true
  name: wanderlust-ingress
  className: nginx
  host: test.yashidevops.xyz
  rewriteTarget: /
